-- Schema de produção do DS List (PostgreSQL).
-- Rodar manualmente uma vez no banco de produção antes do primeiro deploy,
-- já que o perfil "prod" usa ddl-auto=none.

CREATE TABLE tb_game (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(255),
    game_year integer,
    genre varchar(255),
    platforms varchar(255),
    score double precision,
    img_url varchar(255),
    short_description text,
    long_description text
);

CREATE TABLE tb_game_list (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255)
);

CREATE TABLE tb_belonging (
    game_id bigint NOT NULL REFERENCES tb_game,
    list_id bigint NOT NULL REFERENCES tb_game_list,
    position integer,
    PRIMARY KEY (game_id, list_id)
);
